CREATE USER guest1 IDENTIFIED BY guest1 DEFAULT TABLESPACE ELECCIONESTBS;
CREATE USER guest2 IDENTIFIED BY guest2 DEFAULT TABLESPACE ELECCIONESTBS;
CREATE USER guest3 IDENTIFIED BY guest3 DEFAULT TABLESPACE ELECCIONESTBS;
/
CREATE ROLE rol_guest NOT IDENTIFIED;
/
GRANT CONNECT TO rol_guest;
/
GRANT RESOURCES TO rol_guest;
/
GRANT CREATE ANY VIEW TO rol_guest;
/
GRANT EXECUTE ANY TYPE TO rol_guest;
/
GRANT SELECT ON ELECCIONES.ACTA TO rol_guest;
/
GRANT SELECT ON ELECCIONES.DEPARTAMENTO TO rol_guest;
/
GRANT SELECT ON ELECCIONES.ELECCION TO rol_guest;
/
GRANT SELECT ON ELECCIONES.MUNICIPIO TO rol_guest;
/
GRANT SELECT ON ELECCIONES.PARTIDO TO rol_guest;
/
GRANT SELECT ON ELECCIONES.VOTO TO rol_guest;
/
GRANT SELECT ON ELECCIONES.VOTOSPRESIDENTE TO rol_guest;
/
GRANT rol_guest TO guest1;
/
GRANT rol_guest TO guest2;
/
GRANT rol_guest TO guest3;
/