CREATE USER mesas1 IDENTIFIED BY mesas1 DEFAULT TABLESPACE ELECCIONESTBS;
CREATE USER mesas2 IDENTIFIED BY mesas2 DEFAULT TABLESPACE ELECCIONESTBS;
CREATE USER mesas3 IDENTIFIED BY mesas3 DEFAULT TABLESPACE ELECCIONESTBS;
CREATE USER mesas4 IDENTIFIED BY mesas4 DEFAULT TABLESPACE ELECCIONESTBS;
/
CREATE ROLE rol_mesa NOT IDENTIFIED;
/
GRANT CONNECT TO rol_mesa;
/
GRANT SELECT,INSERT ON ELECCIONES.ACTA TO rol_mesa;
/
GRANT SELECT,INSERT ON ELECCIONES.DEPARTAMENTO TO rol_mesa;
/
GRANT SELECT,INSERT ON ELECCIONES.ELECCION TO rol_mesa;
/
GRANT SELECT,INSERT ON ELECCIONES.MUNICIPIO TO rol_mesa;
/
GRANT SELECT,INSERT ON ELECCIONES.PARTIDO TO rol_mesa;
/
GRANT SELECT,INSERT ON ELECCIONES.VOTO TO rol_mesa;
/
GRANT rol_mesa TO mesas1;
/
GRANT rol_mesa TO mesas2;
/
GRANT rol_mesa TO mesas3;
/
GRANT rol_mesa TO mesas4;
/
