CREATE USER admin1 IDENTIFIED BY admin1 DEFAULT TABLESPACE ELECCIONESTBS;
CREATE USER admin2 IDENTIFIED BY admin2 DEFAULT TABLESPACE ELECCIONESTBS;
/
CREATE ROLE rol_admin NOT IDENTIFIED;
/
GRANT CONNECT TO rol_admin;
/
GRANT CREATE USER TO rol_admin;
/
GRANT SELECT,INSERT,UPDATE,DELETE ON ELECCIONES.ACTA TO rol_admin;
/
GRANT SELECT,INSERT,UPDATE,DELETE ON ELECCIONES.DEPARTAMENTO TO rol_admin;
/
GRANT SELECT,INSERT,UPDATE,DELETE ON ELECCIONES.ELECCION TO rol_admin;
/
GRANT SELECT,INSERT,UPDATE,DELETE ON ELECCIONES.MUNICIPIO TO rol_admin;
/
GRANT SELECT,INSERT,UPDATE,DELETE ON ELECCIONES.PARTIDO TO rol_admin;
/
GRANT SELECT,INSERT,UPDATE,DELETE ON ELECCIONES.VOTO TO rol_admin;
/
GRANT rol_admin TO admin1;
/
GRANT rol_admin TO admin2;
/
