CREATE TABLESPACE LIGAPILOTOTBS DATAFILE '/u01/app/oracle/oradata/datafiles/liga_piloto.tbs' 
SIZE 250M
AUTOEXTEND on next 1M
MAXSIZE 500M
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 64K;
/

CREATE USER LIGA_PILOTO PROFILE DEFAULT IDENTIFIED BY LIGA_PILOTO 
DEFAULT TABLESPACE LIGAPILOTOTBS
ACCOUNT UNLOCK;
/
GRANT CONNECT TO LIGA_PILOTO;
GRANT RESOURCE TO LIGA_PILOTO;

/
CREATE USER EQUIPOS PROFILE DEFAULT IDENTIFIED BY EQUIPOS 
DEFAULT TABLESPACE LIGAPILOTOTBS
ACCOUNT UNLOCK;
/
GRANT CONNECT TO EQUIPOS;
GRANT RESOURCE TO EQUIPOS;

/
CREATE USER JORNADAS PROFILE DEFAULT IDENTIFIED BY JORNADAS 
DEFAULT TABLESPACE LIGAPILOTOTBS
ACCOUNT UNLOCK;
/
GRANT CONNECT TO JORNADAS;
GRANT RESOURCE TO JORNADAS;